"""
Command Line Interface (CLI) Module

This module is responsible for parsing input arguments from the terminal.
"""

import argparse


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments for the backend pipeline.

    Returns:
        argparse.Namespace: An object containing all parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Process a single video into an in-memory skeleton and preview outputs"
    )
    parser.add_argument(
        "--input", "-i",
        required=True,
        help="Path to a single video file"
    )
    parser.add_argument(
        "--save-to-disk",
        action="store_true",
        help="Persist extracted skeleton data (JSON) to disk. Previews are generated by default regardless of this flag.",
    )
    parser.add_argument(
        "--async-save",
        action="store_true",
        help="Perform disk writes and preview generation in background threads when persistence is enabled; otherwise previews are generated synchronously.",
    )
    return parser.parse_args()
